project:
  base_path: ./
  ignore:
    path:
      - target
      - .idea
      - .mvn
      - prompt
      - prompt-builder
      - node_modules
      - ai_helper
      - spike
      - doc
      - .git
      - LICENSE.txt
      - package-lock.json
      - "**/ai_helper"
    file:
      - .DS_Store
input:
  prompt_template:
    path: ai_helper/prompt_builder/prompt    
  relative_files:
    template: >
      ```yaml

      {{{content}}}

      ```  
  instruction: |
    
    ## 任务
    我希望 all_files_xml 的标签去掉CDATA，变成普通的XML标签
output:     
  prompt:
    path: .ai_helper/prompt_builder/output/working
    backup_path: .ai_helper/prompt_builder/output/backup
